### ISSUE TITLE
Not working on Windows,..

### ISSUE THREAD

**Issue by nxpatterns** [joeldenning/single-spa-examples#40]

**Comment by internettrans** [comment]
Could you provide the error message you saw in the command prompt? I know that [these lines of code](https://github.com/CanopyTax/single-spa-examples/blob/master/bin/build-code#L4-L5) don't work in windows, but am curious if there is anything else (since I don't have a windows machine myself).

**Comment by bhupendrajoshi** [comment]
'.\bin\build-code' is not recognized as an internal or external command,
operable program or batch file.

**Comment by bhupendrajoshi** [comment]
as a work around I prefixed all the ./bin/build* in the with bash, to run as bash command

like in package.json 
``` "build": "bash ./bin/build-code",```
instead of
``` "build": "./bin/build-code",```

did the same in ./bin/build-code

**Comment by internettrans** [comment]
@bhupendrajoshi would you be able to pull request your changes? I meant to get around to this but haven't had the chance yet.

**Comment by TheMcMurder** [comment]
Prefixing the build instructions with `bash` will only work on windows if you have the command setup in the command prompt or are using the linux subsystem for windows. We'll need to change all of the build scripts to correctly work on Windows (without bash) and Unix based OS's

Taking a look at how other open source projects solve this:
1. Python or other easy to install cross OS scripts (NodeJS)
2. Use NodeJS instead of Bash (Enzyme)

**Comment by internettrans** [comment]
@webia1 @bhupendrajoshi apologies for the slowness in fixing -- it should be fixed now. I changed all bash scripts to be cross platform node scripts. Let me know if you run into any more problems.
