### ISSUE TITLE
Button to show visually which apps are written in each framework (colored border)

### ISSUE THREAD

**Issue by internettrans** [joeldenning/single-spa-examples#9]
See https://github.com/CanopyTax/single-spa-examples/issues/7#issuecomment-260008143

**Comment by TheMcMurder** [comment]
I was thinking about different ways to do this without inter-application communication. I'm probably missing something but wouldn't a button require inter-application communication? 

At a minimum there would need to be a shared config object so that each application could add and remove the colored border on itself? Or Single Spa would have to manage it, In which case my question evolves into where do you put the button? Can the button exist on a child application but be controlled by the parent application?

**Comment by internettrans** [comment]
You're absolutely right, the button will require inter app communication. I actually am almost finished with this feature, I'll be sure to mention you in the pull request for it so you can see.

About where to put the button, having the button in a child application but controlled by the parent application is a valid way of doing (and it's the way I've been planning to implement it). I'm planning on using an Rx ReplaySubject in the parent application, which basically is a single value except when it changes it pushes out its updates to all subscribers. So in all of the child applications, I'll have them subscribe to that ReplaySubject and they will be notified whenever the button is clicked.

**Comment by internettrans** [comment]
How I explained above is of course just one if many ways to do inter app communication. At canopy and also with the dealer socket developers, we've been discussing if we should create a project or add to single-spa itself a way to do inter app communication in a more standardized way.

I would love to hear your thoughts on it, and if you'd like you could even join in on one of our discussions about it sometime

**Comment by TheMcMurder** [comment]
Awesome!! A much better solution than a shared config (pull), I haven't gotten to use RxJS in anything besides sample applications so sometimes I forget it's an option.

As for adding inter app communication to Single-spa itself. That's an interesting idea, I feel like that ultimately comes down to your goal with the project. I'd suggest that if your goal is an opinionated framework then built in communication is essential. If you want single-spa to be more of a configurable library then I'd suggest building an middleware layer, which can contain any implementation of inter app communication, giving implementors a choice between RxJS or something else.

So the question in my mind becomes: Where on this line do you want single-spa to live?

Opinionated Framework (IE Angular) <----------------------------------------> Configurable Library

I should point out that because I'm still working through how single spa works my thoughts could be totally out there.
